from .openduckpro2_config import OpenDuckPro2RoughCfg, OpenDuckPro2RoughCfgPPO
from .openduckpro2_env import OpenDuckPro2Robot
from .openduckpro3_config import OpenDuckPro3RoughCfg, OpenDuckPro3RoughCfgPPO
